//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        public Articulos()
        {
            this.Contratos = new HashSet<Contratos>();
            this.Relacion = new HashSet<Relacion>();
            this.RelacionDos = new HashSet<Relacion>();
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int IdArticulo { get; set; }
        public Nullable<int> CodigoStatus { get; set; }
        public Nullable<int> IdLocalizacion { get; set; }
        public Nullable<System.DateTime> FechaAdquisicion { get; set; }
        public Nullable<System.DateTime> FechaUltimoMovimiento { get; set; }
        public string OtrosDetalles { get; set; }
        public int IdModelo { get; set; }
        public Nullable<int> IdPersonal { get; set; }
        public int IdProveedor { get; set; }
        public double CostoAdquisicion { get; set; }
    
        public virtual Localizaciones Localizaciones { get; set; }
        public virtual Modelos Modelos { get; set; }
        public virtual ICollection<Contratos> Contratos { get; set; }
        public virtual Personals Personals { get; set; }
        public virtual TercerasPersonas TercerasPersonas { get; set; }
        public virtual ICollection<Relacion> Relacion { get; set; }
        public virtual ICollection<Relacion> RelacionDos { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
