//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contratos
    {
        public int IdContrato { get; set; }
        public int IdArticulo { get; set; }
        public int IdTerceraPersona { get; set; }
        public int IdTipoContrato { get; set; }
        public System.DateTime FechaContrato { get; set; }
        public string Detalles { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual TercerasPersonas TercerasPersonas { get; set; }
        public virtual TipoContrato TipoContrato { get; set; }
    }
}
