//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamentos
    {
        public Departamentos()
        {
            this.Personals = new HashSet<Personals>();
        }
    
        public int IdDepartamento { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Personals> Personals { get; set; }
    }
}
