//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnowledgeItem
    {
        public KnowledgeItem()
        {
            this.Ticket = new HashSet<Ticket>();
            this.Comentario = new HashSet<Comentario>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaUltimaModificacion { get; set; }
        public string Creador { get; set; }
        public string Keywords { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Ticket> Ticket { get; set; }
        public virtual ICollection<Comentario> Comentario { get; set; }
    }
}
