//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localizaciones
    {
        public Localizaciones()
        {
            this.Articulos = new HashSet<Articulos>();
        }
    
        public int IdLocalizacion { get; set; }
        public string Direccion { get; set; }
        public string Descripcion { get; set; }
        public string Detalles { get; set; }
    
        public virtual ICollection<Articulos> Articulos { get; set; }
    }
}
