//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelos
    {
        public Modelos()
        {
            this.Articulos = new HashSet<Articulos>();
        }
    
        public int IdModelo { get; set; }
        public string Fabricante { get; set; }
        public string Modelo { get; set; }
        public string Especificaciones { get; set; }
        public int IdTipoArticulo { get; set; }
    
        public virtual ICollection<Articulos> Articulos { get; set; }
        public virtual TipoArticulos TipoArticulos { get; set; }
    }
}
