//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personals
    {
        public Personals()
        {
            this.Articulos = new HashSet<Articulos>();
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int IdPersonal { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Puesto { get; set; }
        public int IdDepartamento { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual ICollection<Articulos> Articulos { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
