//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TercerasPersonas
    {
        public TercerasPersonas()
        {
            this.Contratos = new HashSet<Contratos>();
            this.Articulos = new HashSet<Articulos>();
        }
    
        public int IdTerceraPersona { get; set; }
        public int IdTipoCompania { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Rfc { get; set; }
        public string Detalles { get; set; }
    
        public virtual ICollection<Contratos> Contratos { get; set; }
        public virtual TipoCompania TipoCompania { get; set; }
        public virtual ICollection<Articulos> Articulos { get; set; }
    }
}
