//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Categoria { get; set; }
        public string Prioridad { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string IdCreador { get; set; }
        public System.DateTime FechaUltimaActualizacion { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> KnowledgeItemId { get; set; }
        public Nullable<int> ArticulosIdArticulo { get; set; }
        public Nullable<int> PersonalsIdPersonal { get; set; }
        public string Status { get; set; }
    
        public virtual KnowledgeItem KnowledgeItem { get; set; }
        public virtual Articulos Articulos { get; set; }
        public virtual Personals Personals { get; set; }
    }
}
