//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoContrato
    {
        public TipoContrato()
        {
            this.Contratos = new HashSet<Contratos>();
        }
    
        public int IdTipoContrato { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Contratos> Contratos { get; set; }
    }
}
