//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCompania
    {
        public TipoCompania()
        {
            this.TercerasPersonas = new HashSet<TercerasPersonas>();
        }
    
        public int IdTipoCompania { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<TercerasPersonas> TercerasPersonas { get; set; }
    }
}
